name: Bug report 🐛
description: If something isn't working as expected 🤔.

body:
  - type: textarea
    attributes:
      label: Bug report
      description: Please describe your problem here
    validations:
      required: true

  - type: textarea
    attributes:
      label: Test snippet that reproduces the problem
      description: Provide a minimal test file to demonstrate the issue

  - type: textarea
    attributes:
      label: Expected output
      description: Was the issue reported incorrectly? Or should Cucumber Linter detect an issue with the code but doesn't?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Did Cucumber Linter help you today? Did it make you happy in any way?
      description: |
        Answering this question is not required, but if you have anything positive to share, please do so here!
        Sometimes we get tired of reading bug reports all day and a little positive end note does wonders.
        [Idea by Joey Hess](https://joeyh.name/blog/entry/two_holiday_stories/)
